name: finbert
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - numpy=1.20
  - pandas=1.2
  - nltk=3.6
  - tqdm
  - ipykernel
  - jupyter
  - pip:
      - transformers==4.6.0
      - torch==1.8.1
      - tokenizers==0.10.3
      - sentencepiece==0.1.95
      - scikit-learn==0.24.1
      - textblob